import React from 'react';
import guide from '../content/experiences/guide.json';
import { SpecimenPhoto } from './SpecimenPhoto';
import './adventure.css';
const KEY='dcis-adventure-v1';
type State={mode:'onsite'|'home'|null; page:'trail'|'encounter'|'end'; step:number; answers:string[]; reveal:boolean; photo:boolean};
const fresh=():State=>({mode:null,page:'trail',step:0,answers:[],reveal:false,photo:false});
let memory=fresh();
function load():State {try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v&&['onsite','home',null].includes(v.mode)&&['trail','encounter','end'].includes(v.page)&&Number.isInteger(v.step)&&v.step>=0&&v.step<=3&&Array.isArray(v.answers)&&v.answers.every((a:unknown)=>typeof a==='string')?v:fresh();}catch{return memory;}}
const stops=['stone','local','world'].map(id=>guide.stops.find(s=>s.id===id)!);
const names=['The Pattern Bridge','The Crystal Garden','The Disguise Grotto'];
export function TrailArt({step=0,pattern='patches'}:{step?:number;pattern?:string}) {return <svg className="adventure-world" viewBox="0 0 360 320" role="img" aria-label={`Illustrated story trail: ${Math.min(step,3)} of 3 discoveries. Not a floor plan.`}><defs><linearGradient id="adv-sky" x2="0" y2="1"><stop stopColor="#d5f0ee"/><stop offset="1" stopColor="#f6edce"/></linearGradient><linearGradient id="adv-crystal" x2="1" y2="1"><stop stopColor="#b9f6de"/><stop offset="1" stopColor="#2c8f85"/></linearGradient></defs><rect width="360" height="320" rx="28" fill="url(#adv-sky)"/><circle cx="290" cy="48" r="27" fill="#fff8c7"/><path d="M0 174 Q90 80 184 159 T360 144 V320 H0" fill="#a8c9ac"/><path d="M0 228 Q80 159 185 226 T360 206 V320 H0" fill="#6eaa91"/><path d="M62 289 C-6 194 196 260 157 172 S326 137 280 73" fill="none" stroke="#416b66" strokeWidth="29"/><path d="M62 289 C-6 194 196 260 157 172 S326 137 280 73" fill="none" stroke="#f4d58a" strokeWidth="21" strokeDasharray="2 5"/>
<g transform="translate(26 206)"><path d="M0 43V12Q45-20 90 12V43H66V30Q45 9 24 30V43Z" fill={step>0?'#efb86b':'#f4e6c7'} stroke="#34565a" strokeWidth="3"/>{[12,32,52,72].map(x=><path key={x} d={pattern==='ribbons'?`M${x} 7v15`:`M${x} 10l6 7-7 4`} fill="none" stroke="#99744d" strokeWidth="3"/>)}<text x="45" y="63">01 · COMPARE</text></g>
<g transform="translate(133 105)"><ellipse cx="30" cy="64" rx="47" ry="14" fill="#366f62"/><path d="M-2 54V17L10 0 24 18V61L10 69Z M29 61V-2L44-23 59-2V54L44 68Z M60 60V32L70 20 80 32V60Z" fill={step>1?'url(#adv-crystal)':'#d2dfcc'} stroke="#34565a" strokeWidth="3"/><path d="M10 0V60M44-23V57M70 20V60" stroke="#f7f4cc" strokeWidth="2"/><text x="35" y="94">02 · FIND</text></g>
<g transform="translate(248 25)"><path d="M-12 58L0 15 30 0 60 20 78 67Z" fill={step>2?'#d8a7b1':'#bac3b9'} stroke="#34565a" strokeWidth="3"/><path d="M10 63Q9 24 33 25Q59 26 57 65" fill="#344f5b"/><path d="M23 57L21 40 32 30 45 40 41 58Z" fill={step>2?'#f1cbd4':'#809795'}/><text x="32" y="87">03 · REVEAL</text></g>
<g fill="#fff1b5">{[[29,75],[85,135],[284,212],[315,257]].map(([x,y])=><path key={x} d={`M${x} ${y-6}l2 4 5 2-5 2-2 5-2-5-5-2 5-2Z`}/>)}</g></svg>;}
function Landmark({step}:{step:number}) {return <svg className="adventure-landmark" viewBox="0 0 320 145" role="img" aria-label={['Stylized cut stone patterns','Stylized prisms rising from a host rock','Stylized rose quartz and flint'][step]}>{step===0?<><circle cx="92" cy="72" r="53" fill="#e5c9b4" stroke="#355c59" strokeWidth="3"/>{[[70,45],[104,68],[63,90],[115,99],[119,38],[80,70]].map(([x,y])=><path key={x} d={`M${x} ${y}l12-5 7 12-12 6Z`} fill="#586f65"/>)}<circle cx="232" cy="72" r="53" fill="#c1c8ad" stroke="#355c59" strokeWidth="3"/><path d="M187 48Q215 23 273 58M181 78Q230 54 280 89M191 106Q233 82 270 112" stroke="#456960" strokeWidth="13" fill="none"/></>:step===1?<><path d="M52 119L89 78 230 83 267 121 200 141 100 140Z" fill="#c69886"/><path d="M104 109V43L122 20 142 43V117L122 128Z M171 105V24L190 3 209 24V109L190 123Z" fill="#74baa9" stroke="#315b5c" strokeWidth="3"/><path d="M122 20V117M190 3V111" stroke="#c8f3d9" strokeWidth="3"/></>:<><path d="M35 107L53 45 92 27 132 64 145 119 74 131Z" fill="#dda9b9" stroke="#735b6d" strokeWidth="3"/><path d="M182 116L179 42 236 22 277 64 282 120Z" fill="#ded9b8" stroke="#735b6d" strokeWidth="3"/><ellipse cx="227" cy="71" rx="23" ry="29" fill="#6c726a"/><ellipse cx="263" cy="109" rx="13" ry="10" fill="#6c726a"/></>}</svg>;}
export function Adventure(){const [s,set]=React.useState<State>(load);const [storageIssue,setStorageIssue]=React.useState(false);const stop=stops[Math.min(s.step,2)];const answer=s.answers[s.step];
React.useEffect(()=>{memory=s;try{localStorage.setItem(KEY,JSON.stringify(s));}catch{setStorageIssue(true);}},[s]);
React.useEffect(()=>{window.scrollTo(0,0);},[s.page,s.step]);
function choose(a:string){set({...s,answers:Object.assign([...s.answers],{[s.step]:a})});}
function next(){set({...s,step:s.step+1,page:s.step===2?'end':'trail',reveal:false,photo:false});}
return <section className="adventure"><div className="adventure-top"><a href="#home">← Home</a><span>A Mineral Hall adventure</span><a href="#map">Map ↗</a></div>{storageIssue&&<p role="status">Storage is unavailable. Your trail lasts in this tab, but may not survive a reload.</p>}
{!s.mode?<><p className="adventure-eyebrow">THREE STOPS · ONE NEW WAY TO LOOK</p><h1>Nothing is<br/><em>just a rock.</em></h1><p className="adventure-lead">Build a little world from things you notice in the real Mineral Hall.</p><TrailArt/><div className="adventure-mode"><button className="adv-primary" onClick={()=>set({...s,mode:'onsite'})}>I’m at the museum →</button><button onClick={()=>set({...s,mode:'home',photo:true})}>Try from home · recorded photos</button></div><p className="adv-note">An illustrated story trail, not a floor plan. No scores, no hurry. Keep cases closed and specimens in place.</p></>:
s.page==='trail'?<><p className="adventure-eyebrow">{s.mode==='home'?'PHOTO ADVENTURE':'ON-SITE ADVENTURE'} · {s.step} OF 3 DISCOVERIES</p><h1>{s.step===0?'Look closer.':s.step===1?'A bridge from stone.':'Your garden has grown.'}</h1><p className="adventure-lead">{s.step===0?'Three real displays. Three small surprises. Your observations bring this trail to life.':s.step===1?'You found a pattern. Now find a shape that grew, rather than one that was cut.':'A prism is easy to recognize. What happens when a mineral hides its familiar shape?'}</p><TrailArt step={s.step} pattern={s.answers[0]}/><p className="adv-note">Story trail only — use Map for the museum layout.</p><div className="adv-destination"><span>NEXT · {String(s.step+1).padStart(2,'0')}</span><h2>{names[s.step]}</h2><p>{stop.location.name} · Map {stop.location.mapNumber}</p><button className="adv-primary" onClick={()=>set({...s,page:'encounter'})}>{s.step===0?'Enter the adventure':'Continue the trail'} →</button></div><button className="adv-text" onClick={()=>set({...s,mode:s.mode==='home'?'onsite':'home'})}>Switch to {s.mode==='home'?'on-site':'photo'} mode</button></>:
s.page==='end'?<><p className="adventure-eyebrow">THREE DISCOVERIES · YOUR WORLD, COMPLETE</p><h1>You changed<br/><em>the way you look.</em></h1><TrailArt step={3} pattern={s.answers[0]}/><div className="adv-recap"><h2>A world made from your attention</h2><p><strong>Your bridge:</strong> {s.answers[0]==='ribbons'?'long flowing zones':s.answers[0]==='patches'?'little islands of grains':'a pattern still worth another look'}.</p><p><strong>Your garden:</strong> {s.answers[1]==='faces'?'flat crystal faces':s.answers[1]==='meeting'?'the place crystal meets host rock':'a shape to look for again'}.</p><p><strong>Your surprise:</strong> {s.answers[2]==='both'?'you suspected both could hide a quartz connection':s.answers[2]==='pink'?'the pink rock was your first quartz suspect':s.answers[2]==='flint'?'you looked past the flint’s disguise':'you left room for the unexpected'}.</p><p>Cut circles. Grown prisms. Crystals too small to see. A rock’s outline is only the beginning.</p></div><p className="adventure-lead">Show someone one of these objects. Ask: “What would you miss at first glance?”</p><button className="adv-primary" onClick={()=>set(fresh())}>Play again · make a different world</button><a className="adv-secondary" href="#browse">Explore the collection →</a><p className="adv-note">Completed by your own observations, not verified check-ins. Prototype interpretation; on-site enjoyment still needs visitor testing.</p></>:
<><p className="adventure-eyebrow">ENCOUNTER {s.step+1} / 3 · {s.mode==='home'?'RECORDED PHOTOS':'LOOK AT THE REAL DISPLAY'}</p><h1>{names[s.step]}</h1><Landmark step={s.step}/><p className="adv-note">Interpretive illustration · not an exact specimen drawing</p><div className="adv-location"><strong>{stop.location.name}</strong><span>Map {stop.location.mapNumber}{stop.location.physicalSticker?` · cabinet sticker ${stop.location.physicalSticker}`:''}</span><a href={`#map/minerals/${stop.location.mapNumber}`}>Find this display ↗</a></div><details><summary>Where to look / can’t find it?</summary><p>{stop.find}</p><p>Ask a docent, use the recorded photographs, or choose “not sure” below. No need to open a case or touch a specimen.</p></details>{(s.mode==='home'||s.photo)?<div className="adv-photos">{stop.images.map(img=><figure key={img.src}><SpecimenPhoto src={img.src} alt={img.alt}/><figcaption>{img.alt.replace(' — photographed display detail','')} · recorded photo</figcaption></figure>)}</div>:<button className="adv-secondary" onClick={()=>set({...s,photo:true})}>Use recorded photos instead</button>}
{s.step===0?<><h2>Borrow a pattern for your bridge.</h2><p>Compare the two round samples: granite and amphibolite gneiss. Ignore their matching cut outlines. Which texture would you take into your world?</p><div className="adv-choices"><button aria-pressed={answer==='patches'} onClick={()=>choose('patches')}><b>▧</b> Islands of grains</button><button aria-pressed={answer==='ribbons'} onClick={()=>choose('ribbons')}><b>≋</b> Longer light & dark zones</button></div>{answer&&<div className="adv-response" role="status"><strong>{answer==='ribbons'?'A flowing bridge.':answer==='patches'?'A mosaic bridge.':'Keep the question open.'}</strong><p>The circles were cut by people. The textures belong to the rock. Same outline, different story — your chosen pattern will mark the bridge.</p></div>}</>:
s.step===1?<><h2>Follow a crystal into the rock.</h2><p>Find Beryl & Microcline. Follow one blue-green prism down into its pinkish-brown host. Choose the detail your eye wants to keep.</p><div className="adv-choices"><button aria-pressed={answer==='faces'} onClick={()=>choose('faces')}><b>◇</b> The long, flat faces</button><button aria-pressed={answer==='meeting'} onClick={()=>choose('meeting')}><b>⋈</b> Where crystal meets host</button></div>{answer&&<div className="adv-response" role="status"><strong>{answer==='faces'?'A shape that grew.':answer==='meeting'?'Two names, one specimen.':'A garden for a second look.'}</strong><p>{answer==='faces'?'Beryl commonly grows as prisms. Unlike the cut circles, these forms offer a clue to the mineral itself.':'The card names Beryl & Microcline: contrasting forms together, not two separate display pieces.'} The label points to Mineral Hill, Delaware County. This garden’s story starts nearby, not in a faraway mountain range.</p></div>}</>:
<><h2>Which might have a quartz connection?</h2><p>Look at the pink Rose Quartz and the pale Dover Flint with dark rounded areas. Neither needs a pointed-crystal silhouette. Make a hunch, then turn over the story.</p><div className="adv-choices">{[['pink','The pink mass'],['flint','The flint slab'],['both','Both might'],['unsure','Surprise me']].map(([id,label])=><button key={id} aria-pressed={answer===id} onClick={()=>{choose(id);}}>{label}</button>)}</div>{answer&&!s.reveal&&<button className="adv-primary" onClick={()=>set({...s,reveal:true})}>Turn over the story ↻</button>}{s.reveal&&<div className="adv-response" role="status"><strong>Crystals can hide in plain sight.</strong><p>Rose quartz is a color variety of quartz. Flint belongs to the fine-grained silica family: its crystals can be too small to distinguish with your eyes. No crystal points does not mean no crystals.</p><p>One more disguise: this “World-Wide” cabinet holds rose quartz labelled Paris, Maine and Dover Flint labelled Gloucester, New Jersey. A cabinet heading is not an object’s birthplace.</p></div>}</>}
{s.step<2&&<button className="adv-text" onClick={()=>choose('unsure')}>I’m not sure / I can’t see it clearly</button>}{answer&&(s.step<2||s.reveal)&&<button className="adv-primary" onClick={next}>{s.step===2?'See the world you made':'Add this discovery to the trail'} →</button>}<button className="adv-text" onClick={()=>set({...s,page:'trail'})}>← Back to your trail</button><p className="adv-note">Your choice records what caught your attention; it is not a scored or verified observation.</p></>}
<details className="adv-sources"><summary>About this adventure</summary><p>Based on the DCIS Volunteer Tour Guide Notes (August 2026), featured building stones, Pennsylvania minerals and worldwide collections; specimen details from the existing public Mineral Hall records. Map numbers are app markers, not cabinet stickers.</p><p>Leave cabinets closed and specimens in place. This complete three-encounter prototype saves only on this device.</p></details></section>;}
