import React from 'react';
import { ArrowLeft, ArrowRight, Camera, Check, CircuitBoard, Eye, Info, MapPin, RotateCcw, ScanLine, Volume2, X, Zap } from 'lucide-react';
import { CopperTownScene } from './CopperTownScene';
import './copper-demo.css';

type Stage = 'find'|'extract'|'power';
type Material = 'copper'|'rubber'|null;
type Save = {stage:Stage;mode:'museum'|'photo';extracted:boolean;material:Material;closed:boolean;lit:boolean;insulated:boolean;broken:boolean};
const initial:Save={stage:'find',mode:'photo',extracted:false,material:null,closed:false,lit:false,insulated:false,broken:false};
const key='dcis-copper-encounter-v1';
function restore():Save {try {const s=JSON.parse(localStorage.getItem(key)||'null');if(!s)return initial;return {...initial,stage:['find','extract','power'].includes(s.stage)?s.stage:'find',mode:s.mode==='museum'?'museum':'photo',extracted:s.extracted===true,material:s.material==='copper'||s.material==='rubber'?s.material:null,closed:s.closed===true,lit:s.lit===true,insulated:s.insulated===true,broken:s.broken===true};}catch{return initial;}}
function OreArt({copper=false}:{copper?:boolean}) {return <svg viewBox="0 0 180 120" aria-hidden="true"><defs><linearGradient id={copper?'cu-metal':'cu-stone'} x2=".8" y2="1"><stop stopColor={copper?'#ffe3b5':'#9de4b4'}/><stop offset=".52" stopColor={copper?'#de915d':'#42795b'}/><stop offset="1" stopColor={copper?'#7e3d25':'#173f3e'}/></linearGradient></defs>{copper?<><path d="M38 74C10 6 144 3 143 62S37 109 50 56 134 29 126 66 65 88 69 56 114 41 108 63" fill="none" stroke="url(#cu-metal)" strokeWidth="12"/><path d="m108 63 41 33" stroke="#dc9a67" strokeWidth="10" strokeLinecap="round"/></>:<><path d="m21 82 9-40 34-24 45 7 38 27 12 39-29 13-66 1Z" fill="url(#cu-stone)"/><path d="m30 42 44 12-10 51M74 54l35-29 12 48 26-21M21 82l53-28 47 19 9 31" fill="none" stroke="#a7cf9580" strokeWidth="2"/><path d="m58 36 19 7-3 16-21-3Zm40 28 11-11 16 7-8 15ZM44 74l12-7 10 16-17 8Z" fill="#70cb91"/></>}</svg>}
export function CopperDemo(){
 const [s,set]=React.useState<Save>(restore),[processing,setProcessing]=React.useState(false),[status,setStatus]=React.useState(''),[arRequest,setARRequest]=React.useState(0),[exitARRequest,setExitARRequest]=React.useState(0),[inAR,setInAR]=React.useState(false),[camera,setCamera]=React.useState(false),[cameraPending,setCameraPending]=React.useState(false),[details,setDetails]=React.useState(false),[storageWarning,setStorageWarning]=React.useState(false),[sound,setSound]=React.useState(false);
 const video=React.useRef<HTMLVideoElement>(null),stream=React.useRef<MediaStream|null>(null),timer=React.useRef<ReturnType<typeof setTimeout>|null>(null),cameraGeneration=React.useRef(0),audio=React.useRef<AudioContext|null>(null);
 const powered=s.stage==='power'&&s.material==='copper'&&s.closed,complete=s.lit&&s.insulated&&s.broken;
 const stopCamera=React.useCallback(()=>{cameraGeneration.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false);setCameraPending(false);},[]);
 React.useEffect(()=>{window.scrollTo(0,0);},[s.stage]);
 React.useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(s));}catch{setStorageWarning(true);}},[s]);
 React.useEffect(()=>{if(video.current&&stream.current)video.current.srcObject=stream.current;},[camera]);
 React.useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);cameraGeneration.current++;stream.current?.getTracks().forEach(t=>t.stop());void audio.current?.close();},[]);
 React.useEffect(()=>{const hide=()=>{if(document.hidden)stopCamera();};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[stopCamera]);
 React.useEffect(()=>{if(!details)return;const previous=document.activeElement as HTMLElement|null;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setDetails(false);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.cu-info button,.cu-info a'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus();};},[details]);
 function chime(){if(!sound)return;try{audio.current??=new AudioContext();const ctx=audio.current;void ctx.resume();[261.63,329.63,392,523.25].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(.055,ctx.currentTime+i*.08+.015);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.08+.8);o.connect(g).connect(ctx.destination);o.start(ctx.currentTime+i*.08);o.stop(ctx.currentTime+i*.08+.85);});}catch{/* audio is optional */}}
 function experiment(material:Material,closed:boolean){const lit=material==='copper'&&closed;if(lit&&!powered)chime();set(v=>({...v,material,closed,lit:v.lit||lit,insulated:v.insulated||(material==='rubber'&&closed),broken:v.broken||(v.lit&&!closed)}));}
 async function openCamera(){if(camera){stopCamera();return;}const generation=++cameraGeneration.current;setCameraPending(true);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unavailable');const st=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(generation!==cameraGeneration.current){st.getTracks().forEach(t=>t.stop());return;}stream.current=st;setCamera(true);setStatus('Camera preview: the model stays on your screen, not on a tracked surface.');}catch{setStatus('Camera unavailable or permission declined. The complete 3D experiment still works.');}finally{if(generation===cameraGeneration.current)setCameraPending(false);}}
 function extract(){setProcessing(true);timer.current=setTimeout(()=>{set(v=>({...v,extracted:true}));setProcessing(false);},1600);}
 function reset(){if(timer.current)clearTimeout(timer.current);setProcessing(false);set({...initial,mode:s.mode});setStatus('');stopCamera();setExitARRequest(v=>v+1);}
 return <main className={`copper-demo ${powered?'is-powered':''} ${inAR?'is-ar':''} ${camera?'is-camera':''}`} data-stage={s.stage} data-complete={complete}>
  <header className="cu-top"><a href="#hunt" aria-label="Back to museum hunt"><ArrowLeft size={17}/><span>DCIS <b>FIELD LAB</b></span></a><div><button aria-pressed={sound} aria-label="Sound effects" onClick={()=>setSound(v=>!v)}><Volume2 size={17}/><span>{sound?'Sound on':'Sound off'}</span></button><button aria-label="Restart copper experiment" onClick={reset}><RotateCcw size={17}/></button><button aria-label="About this experiment" onClick={()=>setDetails(v=>!v)}><Info size={18}/></button></div></header>
  <div className="cu-layout"><section className="cu-story">
   <div className="cu-eyebrow"><span/> MINERAL HALL / EXPERIMENT 01</div>
   <h1>A little rock.<br/><em>A brighter world.</em></h1>
   <p className="cu-deck">Find the hidden metal. Make the connection.</p>
   <nav className="cu-steps" aria-label="Experiment steps">{(['find','extract','power'] as Stage[]).map((stage,i)=><button key={stage} aria-current={s.stage===stage?'step':undefined} disabled={stage==='extract'&&s.stage==='find'||stage==='power'&&!s.extracted} onClick={()=>set(v=>({...v,stage}))}><span>{i+1}</span>{['Find','Reveal','Power'][i]}</button>)}</nav>
   {s.stage==='find'&&<article className="cu-card cu-find"><div className="cu-card-heading"><span className="cu-tag">YOUR REAL-WORLD CLUE</span><MapPin size={18}/></div><h2>Not all treasure shines.</h2><p>Find the rough rock with green patches in the <strong>Dr. George Smith Collection.</strong></p><figure><img src="/assets/mineral-hall/DCIS-WR-000389-normal.webp" alt="Actual DCIS malachite specimen, with green patches on a rough dark rock and its label"/><figcaption><span>THE ACTUAL MUSEUM SPECIMEN</span><b>Malachite</b></figcaption></figure><p className="cu-location">Wall cabinet · map 11 · top specimen shelf, left.<br/>Look through the glass; leave the specimen in place.</p><a className="cu-map" href="#map/minerals/11"><MapPin size={14}/> Show me the cabinet <ArrowRight size={14}/></a><div className="cu-find-actions"><button className="cu-primary" onClick={()=>set(v=>({...v,mode:'museum',stage:'extract'}))}>I found the green patches <ArrowRight size={17}/></button><button className="cu-text-button" onClick={()=>set(v=>({...v,mode:'photo',stage:'extract'}))}>Not there? Explore this photograph →</button></div></article>}
   {s.stage==='extract'&&<article className="cu-card cu-extract"><span className="cu-tag">THE SURPRISE INSIDE</span><h2>Green mineral.<br/>Reddish metal.</h2><p>Malachite contains <strong>copper</strong>—the metal used in electrical wiring. But a rock is not a ready-made wire.</p><div className={`cu-transformation ${processing?'processing':''} ${s.extracted?'extracted':''}`}><div className="cu-ore"><OreArt/><span>MINERAL</span></div><div className="cu-process-arrow"><span>→</span><small>{processing?'PROCESSING…':'EXTRACT & REFINE'}</small></div><div className="cu-wire"><OreArt copper/><span>COPPER WIRE</span></div></div><p className="cu-science">Extraction separates copper from its compounds. Refining purifies it; drawing shapes the metal into wire.</p><p className="cu-caption">Simplified illustration, not a treatment of this museum specimen. Its individual mining history is unknown.</p>{!s.extracted?<button className="cu-primary" disabled={processing} onClick={extract}>{processing?'Following the copper…':'Reveal the copper connection'}<Zap size={17}/></button>:<><div className="cu-unlocked"><Check size={16}/> Copper connection discovered</div><button className="cu-primary" onClick={()=>set(v=>({...v,stage:'power'}))}>Bring the town to life <ArrowRight size={17}/></button></>}</article>}
   {s.stage==='power'&&<article className="cu-card cu-power"><span className="cu-tag">YOUR POCKET-SIZED EXPERIMENT</span><h2>{complete?'You made the connection.':powered?'You brought it to life.':'The town needs a connection.'}</h2><p>{powered?'Copper carries electric current. The battery supplies the energy—not the mineral.':'Bridge the gap, then close the switch. What will let current reach the town?'}</p><div className="cu-materials" aria-label="Choose bridge material"><button aria-pressed={s.material==='copper'} onClick={()=>experiment('copper',s.closed)}><span className="cu-swatch copper"/><span><b>Copper</b><small>metal conductor</small></span>{s.material==='copper'&&<Check size={16}/>}</button><button aria-pressed={s.material==='rubber'} onClick={()=>experiment('rubber',s.closed)}><span className="cu-swatch rubber"/><span><b>Rubber</b><small>insulating material</small></span>{s.material==='rubber'&&<Check size={16}/>}</button></div><button className={`cu-switch ${s.closed?'closed':''}`} aria-pressed={s.closed} onClick={()=>experiment(s.material,!s.closed)}><span className="cu-toggle"><i/></span><span>{s.closed?'Open the switch':'Close the switch'}</span><Zap size={19}/></button><div className={`cu-feedback ${powered?'live':''}`} role="status"><i/>{powered?'Circuit complete. Watch the town wake up.':s.closed&&s.material==='rubber'?'Rubber interrupts the conducting path. The lights stay off.':s.closed&&!s.material?'The switch is closed, but the material gap is still empty.':s.lit?'An open switch breaks the circuit. The town goes dark.':'No complete path yet. The battery is waiting.'}</div><div className="cu-challenges"><span><b>Try all three</b> · no wrong turns</span><p className={s.lit?'done':''}><Check size={14}/> Light it with copper</p><p className={s.insulated?'done':''}><Check size={14}/> Swap in rubber with the switch closed</p><p className={s.broken?'done':''}><Check size={14}/> Open the switch after lighting it</p></div>{complete&&<div className="cu-discovery"><span>DISCOVERY MADE</span><strong>From green patches to glowing windows.</strong><p>Look back at the malachite. Its copper is chemically bound inside a mineral—not already a wire. Processing makes the metal available for uses like this.</p><a href="#hunt">Find your next museum surprise <ArrowRight size={16}/></a></div>}</article>}
   <div className="cu-source-line"><span>{s.mode==='museum'?'Museum find · self-reported':'Photo exploration'}</span><button onClick={()=>setDetails(v=>!v)}>From the docent’s guide ↗</button></div>
  </section>
  <section className="cu-laboratory" aria-label="Interactive copper town experiment">
   <div className="cu-scene-head"><div><span className="cu-tag">THE COPPER CONNECTION</span><h2>{powered?'Let there be light.':'A town waiting for a spark.'}</h2></div><span className={`cu-power-led ${powered?'on':''}`}><i/>{powered?'CURRENT FLOWING':'CIRCUIT OPEN'}</span></div>
   <div className="cu-viewport">{camera&&<video ref={video} autoPlay muted playsInline className="cu-camera-feed" aria-label="Local camera preview"/>}<CopperTownScene material={s.stage==='power'?s.material:null} closed={s.stage==='power'&&s.closed} arRequest={arRequest} exitARRequest={exitARRequest} onStatus={setStatus} onARChange={setInAR} cameraBackdrop={camera}/><div className="cu-scene-label"><span>{inAR?'SURFACE-TRACKED AR':camera?'CAMERA PREVIEW · NOT SURFACE-TRACKED':'ILLUSTRATIVE 3D MODEL · DRAG TO EXPLORE'}</span></div>{s.stage!=='power'&&<div className="cu-town-prompt"><CircuitBoard size={20}/><span>Discover the copper in a real museum mineral.<br/><b>Then use it to complete this circuit.</b></span></div>}</div>
   <div className="cu-ar-tools"><button className="cu-ar-button" onClick={()=>{stopCamera();if(inAR)setExitARRequest(v=>v+1);else setARRequest(v=>v+1);}}><ScanLine size={19}/><span>{inAR?'Exit AR':'Place in your space'}<small>{inAR?'Return to the 3D experiment':'Surface-tracked AR · supported phones'}</small></span></button><button aria-pressed={camera} disabled={cameraPending||inAR} className="cu-camera-button" onClick={openCamera}><Camera size={18}/><span>{camera?'Stop camera':cameraPending?'Opening camera…':'Camera preview'}<small>No surface tracking</small></span></button></div>
   {status&&<p className="cu-device-status" role="status">{status}<button aria-label="Dismiss device message" onClick={()=>setStatus('')}><X size={14}/></button></p>}
   <p className="cu-camera-note">Stay still in a clear space. Camera access is optional; this demo does not upload or record it. Physical-phone AR testing is still pending.</p>
  </section></div>
  {storageWarning&&<p className="cu-storage" role="status">Progress cannot be saved on this device. You can still finish here.</p>}
  {details&&<div className="cu-info-backdrop" onClick={()=>setDetails(false)}><section className="cu-info" role="dialog" aria-modal="true" aria-label="About the copper experiment" onClick={e=>e.stopPropagation()}><button className="cu-info-close" aria-label="Close information" autoFocus onClick={()=>setDetails(false)}><X/></button><span className="cu-tag">OBJECT FIRST. STORY SECOND.</span><h2>A real collection.<br/>A model you can play with.</h2><p>The August 2026 DCIS docent notes highlight George Smith’s collection and how mineral resources powered and built everyday life—including copper wiring.</p><p>The photograph shows catalog record <b>DCIS-WR-000389</b>, malachite in the Dr. George Smith wall cabinet. The town is an illustration, not historic Media or a reconstruction of this specimen’s history.</p><p>Copper connects a battery-powered circuit here. It does not generate electricity. Moving pulses illustrate a complete path; they are not to-scale electrons or a measurement.</p><p>Real copper extraction is a chemical process. No heating, collecting, touching or treating museum specimens is part of this activity.</p><p>Interactive surface-tracked AR requires WebXR, hit testing and DOM overlay support. Camera preview is an untracked overlay. Neither mode identifies exhibits automatically.</p><div className="cu-references"><a href="https://periodic-table.rsc.org/element/29/Copper" target="_blank" rel="noreferrer">Royal Society of Chemistry · copper ↗</a><a href="https://edu.rsc.org/experiments/extracting-copper-from-copperii-carbonate/478.article" target="_blank" rel="noreferrer">RSC · the chemistry behind extraction ↗</a></div><button className="cu-primary" onClick={()=>setDetails(false)}>Back to the experiment</button></section></div>}
 </main>;
}
