import React from 'react';
import guide from '../content/experiences/guide.json';
import mystery from '../content/experiences/mystery.json';
import './experiences.css';
const KEY = 'dcis-experiences-v1';
type Saved = {guide: string; mystery: string; active: 'guide'|'mystery'; answers: Record<string,string>; light: 'normal'|'uv'};
const fresh = (): Saved => ({guide:'smith',mystery:'find',active:'guide',answers:{},light:'normal'});
let memory: Saved = fresh();
let storageUnavailable = false;
export function readExperience(): Saved {
  if (storageUnavailable) return memory;
  try {
    const s = JSON.parse(localStorage.getItem(KEY) || 'null');
    if (!s || !['guide','mystery'].includes(s.active) || ![...guide.stops.map(x=>x.id),'end'].includes(s.guide) || !mystery.nodes.some(x=>x.id===s.mystery) || !['normal','uv'].includes(s.light) || !s.answers || typeof s.answers!=='object' || Array.isArray(s.answers)) return fresh();
    return {guide:s.guide,mystery:s.mystery,active:s.active,light:s.light,answers:Object.fromEntries(Object.entries(s.answers).filter(([id,v])=>mystery.nodes.find(n=>n.id===id)?.choices?.some(c=>c.id===v)))} as Saved;
  } catch { return memory; }
}
export function resumeExperience() { const s=readExperience(); return `#${s.active}/${s[s.active]}`; }
const go = (route:string) => { window.location.hash=route; };
function Photo({src,alt,label}:{src:string;alt:string;label?:string}) { const [failed,setFailed]=React.useState(false); return <figure className="experience-photo">{failed?<p>Photograph unavailable. Follow the written observation below, or continue without comparing.</p>:<img src={src} alt={alt} onError={()=>setFailed(true)}/ >}{label&&<figcaption>{label} · recorded photograph</figcaption>}</figure>; }
function Location({location}:{location:{name:string;mapNumber:string;physicalSticker:string|null}}) {return <p className="experience-location"><strong>{location.name}</strong><span>Map {location.mapNumber}{location.physicalSticker ? ` · Cabinet sticker ${location.physicalSticker}`:''}</span></p>;}
function More({label,children}:{label:string;children:React.ReactNode}){return <details><summary>{label}</summary>{children}</details>;}
export function ExperienceHome({onBrowse,onMap}:{onBrowse:()=>void;onMap:()=>void}) {
 const s=readExperience();
 return <section className="screen experience-home"><p className="kicker">Look closer · Mineral Hall</p><h1>There’s more to a rock<br/>than meets the eye.</h1><p>Follow a docent-inspired story, or investigate one surprising specimen.</p><div className="experience-doors"><a href={`#guide/${s.guide}`}><img src={guide.stops[1].images[0].src} alt="Beryl prisms in their host rock"/><div><small>Five stops · At your pace</small><h2>Look beyond the sparkle</h2><p>{guide.subtitle}</p><strong>{s.guide==='smith'?'Start the Mineral Hall guide':'Resume the Mineral Hall guide'} →</strong></div></a><a href={`#mystery/${s.mystery}`}><img src="/assets/mineral-hall/DCIS-WR-000037-uv.webp" alt="Scheelite photographed under ultraviolet illumination"/><div><small>A photo investigation · No score</small><h2>{mystery.title}</h2><p>{mystery.subtitle}</p><strong>{s.mystery==='find'?'Try the mystery':'Resume the mystery'} →</strong></div></a></div><div className="experience-actions"><button onClick={onMap}>Open first-floor map</button><button onClick={onBrowse}>Browse minerals & displays</button><a href="#guide/list">Choose a guide stop</a></div><p className="experience-note">Prototype interpretation, not an institutionally approved catalog. Recorded photos work even when a live demonstration is unavailable.</p></section>;
}
export function Experiences({route,onMap}:{route:string;onMap:(id:string)=>void}) {
 const [saved,setSaved]=React.useState<Saved>(readExperience);
 const [storageIssue,setStorageIssue]=React.useState(false);
 const [mode,id]=route.replace(/^#/,'').split('/');
 const stop=guide.stops.find(s=>s.id===id);
 const node=mystery.nodes.find(n=>n.id===id);
 React.useEffect(()=>{if(mode==='guide'&&(stop||id==='end'))setSaved(s=>({...s,guide:id,active:'guide'})); if(mode==='mystery'&&node)setSaved(s=>({...s,mystery:id,active:'mystery'})); window.scrollTo(0,0);},[route]);
 React.useEffect(()=>{memory=saved;try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{storageUnavailable=true;setStorageIssue(true);}},[saved]);
 function reset(){const next=mode==='mystery'?{...saved,mystery:'find',answers:{},light:'normal' as const}:{...saved,guide:'smith'};setSaved(next);go(`${mode}/${mode==='mystery'?'find':'smith'}`);}
 const selected=node?.choices?.find(c=>c.id===saved.answers[node.id]);
 return <section className="screen experience" key={route}><div className="experience-toolbar"><a href="#home">← Home</a><a href="#guide/list">Guide stop list</a><button onClick={reset}>Restart {mode==='mystery'?'mystery':'guide'}</button></div>{storageIssue&&<p role="status">Device storage is unavailable. Progress lasts while this experience stays open.</p>}
 {mode==='guide'&&id==='list'?<><p className="kicker">Docent-inspired guide</p><h1>{guide.title}</h1><p>{guide.introduction}</p><p className="experience-note">{guide.orientation}</p><a className="experience-primary" href={`#guide/${saved.guide}`}>Resume guide</a><ol className="experience-stop-list">{guide.stops.map(s=><li key={s.id}><a href={`#guide/${s.id}`}><strong>{s.title}</strong><span>{s.location.name} · Map {s.location.mapNumber}</span></a></li>)}</ol><p>{guide.safety}</p></>:
 mode==='guide'&&id==='end'?<div className="experience-finish"><p className="kicker">Five ways of looking</p><h1>{guide.finish.title}</h1><p>{guide.finish.text}</p><a className="experience-primary" href="#mystery/find">{guide.finish.primaryAction.label}</a><a href="#guide/list">{guide.finish.secondaryAction.label}</a></div>:
 mode==='guide'&&stop?<><p className="kicker">Docent-inspired guide · Stop {guide.stops.indexOf(stop)+1} of {guide.stops.length}</p><h1>{stop.title}</h1><Location location={stop.location}/><div className="experience-layout"><div className="experience-photos">{stop.images.map(img=><Photo key={img.src} {...img}/>)}</div><div className="experience-copy"><p className="experience-lead">{stop.introduction}</p><More label="Find this specimen"><p>{stop.find}</p><button onClick={()=>onMap(stop.location.mapNumber)}>Show Map {stop.location.mapNumber}</button><p className="experience-note">{guide.orientation}</p></More><article className="experience-observation"><h2>Look closely</h2><p>{stop.observation}</p></article><More label="The specimen’s story"><p>{stop.objectStory}</p></More><More label="The wider hall story"><p>{stop.hallContext}</p></More><More label={stop.deeper.label}><p>{stop.deeper.text}</p></More><More label={stop.notFound.label}><p>{stop.notFound.text}</p><a href={`#guide/${stop.nextStopId}`}>Continue with photographs / skip this stop</a></More><More label="Visiting safely"><p>{guide.safety}</p></More><div className="experience-actions"><a href={`#guide/${guide.stops[guide.stops.indexOf(stop)-1]?.id||'list'}`}>← Back</a><a className="experience-primary" href={`#guide/${stop.nextStopId}`}>{stop.nextStopId==='end'?'Finish guide':'Next stop'} →</a></div><p className="experience-note">Next: {stop.nextDestination}</p><a href={`#guide/${stop.nextStopId}`}>Skip this stop</a></div></div></>:
 mode==='mystery'&&node?<><p className="kicker">Hidden Appearance · An unscored investigation</p><h1>{node.title}</h1><Location location={mystery.location}/><div className="experience-layout"><div>{node.image&&<Photo {...node.image}/ >}{node.states&&<><div className="experience-toggle" role="group" aria-label="Recorded lighting view">{node.states.map(s=><button key={s.id} aria-pressed={saved.light===s.id} onClick={()=>setSaved({...saved,light:s.id as 'normal'|'uv'})}>{s.label}</button>)}</div>{node.states.filter(s=>s.id===saved.light).map(s=><React.Fragment key={s.id}><Photo {...s.image}/><p>{s.caption}</p></React.Fragment>)}<p className="experience-note">{node.comparisonNote}</p></>}{!node.image&&!node.states&&<Photo {...mystery.nodes[0].image!}/>}</div><div className="experience-copy"><p className="experience-lead">{node.text}</p><p className="experience-safety">{mystery.safety}</p>{node.choices&&<div className="experience-choices">{node.choices.map(c=><button key={c.id} aria-pressed={selected?.id===c.id} onClick={()=>setSaved({...saved,answers:{...saved.answers,[node.id]:c.id}})}>{c.label}</button>)}</div>}{selected&&<div className="experience-response" role="status"><p>{selected.response}</p><button className="experience-primary" onClick={()=>go(`mystery/${selected.next}`)}>Continue →</button></div>}{node.deeper&&<More label={node.deeper.label}><p>{node.deeper.text}</p></More>}{node.next&&<a className="experience-primary" href={`#mystery/${node.next}`}>{node.nextLabel} →</a>}{node.actions&&<div className="experience-actions">{node.actions.map(a=><a key={a.label} href={a.nodeId?`#mystery/${a.nodeId}`:`#guide/${a.stopId}`}>{a.label} →</a>)}</div>}<div className="experience-actions"><a href={mystery.nodes.indexOf(node)>0?`#mystery/${mystery.nodes[mystery.nodes.indexOf(node)-1].id}`:'#home'}>← Back</a><button onClick={()=>onMap(mystery.location.mapNumber)}>Find on Map 4</button></div></div></div></>:<><h1>Choose where to begin</h1><a href="#guide/list">Open the guide stop list</a><a href="#mystery/find">Start Hidden Appearance</a></>}
 </section>;
}
