// Generated by scripts/export-public.mjs from curated public content. Do not edit.
export type MineralMapItem = { id: string; displayId: string; label: string; summary: string; x: number; y: number; width: number; height: number };
export type MineralSpecimenRecord = { id: string; name: string; type: string; displayId: string; displayLabel: string; description?: string; hook?: string; observationPrompt?: string; images?: {src: string; alt: string; label?: string}[] };
export const mineralBrowseDisplays: Pick<MineralMapItem, 'id' | 'displayId' | 'label' | 'summary'>[] = [
  {
    "id": "island",
    "displayId": "MH-WORK-MINERAL-ISLAND",
    "label": "Island collection",
    "summary": "Explore a selection from the unnumbered island cases. Find shapes and textures without assigning objects to a particular side."
  }
];
export const mineralPublicNotice = "Prototype reference, not an institutionally approved catalog. Selected labels only; identifications may be incomplete. Check the display labels.";
export const mineralMapItems: MineralMapItem[] = [
  {
    "id": "entry",
    "displayId": "MH-DISP-ENTRY-001",
    "label": "Entry",
    "summary": "Entrance to Mineral Hall from the inner entrance.",
    "x": 310,
    "y": 890,
    "width": 126,
    "height": 54
  },
  {
    "id": "shells",
    "displayId": "MH-DISP-SHELLS-001",
    "label": "Shells",
    "summary": "Shell display near the Mineral Hall door. Contents may vary.",
    "x": 480,
    "y": 805,
    "width": 116,
    "height": 54
  },
  {
    "id": "1",
    "displayId": "MH-DISP-001",
    "label": "1 Branegan",
    "summary": "Branegan Cabinet. Inner-wall run after shells; Branegan Cabinet",
    "x": 442,
    "y": 700,
    "width": 158,
    "height": 54
  },
  {
    "id": "2",
    "displayId": "MH-DISP-002",
    "label": "2 Local Stones",
    "summary": "Branegan Cabinet B / Local Building Stones. Next inner-wall case; Branegan Cabinet B / Local Building Stones",
    "x": 442,
    "y": 550,
    "width": 150,
    "height": 54
  },
  {
    "id": "3",
    "displayId": "MH-DISP-003",
    "label": "3 PA",
    "summary": "Minerals from Pennsylvania. Interior wall of deeper L recess",
    "x": 354,
    "y": 447,
    "width": 146,
    "height": 54
  },
  {
    "id": "4",
    "displayId": "MH-DISP-004",
    "label": "4 Fluorescent",
    "summary": "Fluorescent mineral case. Interior wall of deeper L recess; fluorescent case",
    "x": 255,
    "y": 447,
    "width": 150,
    "height": 54
  },
  {
    "id": "5",
    "displayId": "MH-DISP-005",
    "label": "5 U.S.",
    "summary": "Minerals from United States. Standalone inner wall",
    "x": 105,
    "y": 352,
    "width": 142,
    "height": 54
  },
  {
    "id": "6",
    "displayId": "MH-DISP-006",
    "label": "6 New Acq.",
    "summary": "Minerals from World-Wide (New Acquisitions). First case of back-wall run",
    "x": 170,
    "y": 266,
    "width": 158,
    "height": 54
  },
  {
    "id": "7",
    "displayId": "MH-DISP-007",
    "label": "7 World",
    "summary": "Minerals from World-Wide. Back-wall run after 6",
    "x": 310,
    "y": 266,
    "width": 134,
    "height": 54
  },
  {
    "id": "8",
    "displayId": "MH-DISP-008",
    "label": "8 Reynolds",
    "summary": "D. Richard Reynolds memorial cabinet. Back-wall run after 7",
    "x": 435,
    "y": 266,
    "width": 134,
    "height": 54
  },
  {
    "id": "9",
    "displayId": "MH-DISP-009",
    "label": "9 Arndt",
    "summary": "Harold W. Arndt Collection. Last back-wall case before corner door",
    "x": 550,
    "y": 266,
    "width": 144,
    "height": 54
  },
  {
    "id": "10",
    "displayId": "MH-DISP-010",
    "label": "10 Sill",
    "summary": "First window-sill mineral display. First window sill",
    "x": 748,
    "y": 335,
    "width": 116,
    "height": 48
  },
  {
    "id": "11",
    "displayId": "MH-DISP-011",
    "label": "11 Wall",
    "summary": "Minerals from the Dr. George Smith Collection — about 1835. Between first and second windows, wall level",
    "x": 753,
    "y": 457,
    "width": 116,
    "height": 48
  },
  {
    "id": "12",
    "displayId": "MH-DISP-012",
    "label": "12 Ground",
    "summary": "Four large mineral specimens under acrylic covers. Between first and second windows, ground level",
    "x": 680,
    "y": 457,
    "width": 116,
    "height": 48
  },
  {
    "id": "13",
    "displayId": "MH-DISP-013",
    "label": "13 Sill",
    "summary": "Second window-sill mineral display. Second window sill",
    "x": 749,
    "y": 595,
    "width": 116,
    "height": 48
  },
  {
    "id": "14",
    "displayId": "MH-DISP-014",
    "label": "14 Ground",
    "summary": "Petrified-wood display. Between second and third windows, ground level",
    "x": 680,
    "y": 735,
    "width": 116,
    "height": 48
  },
  {
    "id": "15",
    "displayId": "MH-DISP-015",
    "label": "15 Wall",
    "summary": "Philadelphia Region / Coaquannock framed map. Between second and third windows, wall level",
    "x": 753,
    "y": 735,
    "width": 116,
    "height": 48
  },
  {
    "id": "16",
    "displayId": "MH-DISP-016",
    "label": "16 Sill",
    "summary": "Third window-sill mineral display. Third window sill",
    "x": 749,
    "y": 850,
    "width": 116,
    "height": 48
  },
  {
    "id": "17",
    "displayId": "MH-DISP-017",
    "label": "17 Cassin",
    "summary": "John Cassin display and mining-district map. Window-side wall immediately right of last window, near corner; John Cassin",
    "x": 755,
    "y": 930,
    "width": 104,
    "height": 48
  },
  {
    "id": "18",
    "displayId": "MH-DISP-018",
    "label": "18 Corner",
    "summary": "Corner specimen cabinet / left unit of 18–19 pair. Starts at corner",
    "x": 688,
    "y": 965,
    "width": 104,
    "height": 48
  },
  {
    "id": "19",
    "displayId": "MH-DISP-019",
    "label": "19 Near door",
    "summary": "Door-side specimen cabinet / right unit of 18–19 pair. Closer to Special Collections/front-wall door",
    "x": 621,
    "y": 965,
    "width": 126,
    "height": 48
  }
];
export const mineralSpecimenRecords: MineralSpecimenRecord[] = [
  {
    "id": "MH-SPEC-003",
    "name": "Quartz var. Smoky",
    "type": "specimen/group label",
    "displayId": "MH-DISP-010",
    "displayLabel": "Case 10 / First window-sill mineral display"
  },
  {
    "id": "MH-SPEC-004",
    "name": "Barite on Fluorite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-010",
    "displayLabel": "Case 10 / First window-sill mineral display"
  },
  {
    "id": "MH-SPEC-005",
    "name": "Quartz var. Rose",
    "type": "specimen/group label",
    "displayId": "MH-DISP-013",
    "displayLabel": "Case 13 / Second window-sill mineral display"
  },
  {
    "id": "MH-SPEC-006",
    "name": "Limonite/Goethite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-013",
    "displayLabel": "Case 13 / Second window-sill mineral display"
  },
  {
    "id": "MH-SPEC-007",
    "name": "Petrified Wood",
    "type": "specimen/group label",
    "displayId": "MH-DISP-014",
    "displayLabel": "Case 14 / Petrified-wood display"
  },
  {
    "id": "MH-SPEC-008",
    "name": "Datolite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-016",
    "displayLabel": "Case 16 / Third window-sill mineral display"
  },
  {
    "id": "MH-SPEC-009",
    "name": "Calcite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-016",
    "displayLabel": "Case 16 / Third window-sill mineral display"
  },
  {
    "id": "MH-SPEC-045",
    "name": "Orthoclase, variety Cassinite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-017",
    "displayLabel": "Case 17 / John Cassin display and mining-district map"
  },
  {
    "id": "MH-EXH-MAP-001",
    "name": "Branegan Cabinet",
    "type": "exhibit identity",
    "displayId": "MH-DISP-001",
    "displayLabel": "Case 1 / Branegan Cabinet"
  },
  {
    "id": "MH-EXH-MAP-002",
    "name": "Branegan Cabinet B / Local Building Stones",
    "type": "exhibit identity",
    "displayId": "MH-DISP-002",
    "displayLabel": "Case 2 / Branegan Cabinet B / Local Building Stones"
  },
  {
    "id": "MH-EXH-MAP-003",
    "name": "Minerals from Pennsylvania",
    "type": "exhibit identity",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania"
  },
  {
    "id": "MH-EXH-MAP-004",
    "name": "Fluorescent mineral case",
    "type": "exhibit identity",
    "displayId": "MH-DISP-004",
    "displayLabel": "Case 4 / Fluorescent mineral case"
  },
  {
    "id": "MH-EXH-MAP-005",
    "name": "Minerals from United States",
    "type": "exhibit identity",
    "displayId": "MH-DISP-005",
    "displayLabel": "Case 5 / Minerals from United States"
  },
  {
    "id": "MH-EXH-MAP-006",
    "name": "Minerals from World-Wide (New Acquisitions)",
    "type": "exhibit identity",
    "displayId": "MH-DISP-006",
    "displayLabel": "Case 6 / Minerals from World-Wide (New Acquisitions)"
  },
  {
    "id": "MH-EXH-MAP-007",
    "name": "Minerals from World-Wide",
    "type": "exhibit identity",
    "displayId": "MH-DISP-007",
    "displayLabel": "Case 7 / Minerals from World-Wide"
  },
  {
    "id": "MH-EXH-MAP-008",
    "name": "D. Richard Reynolds memorial cabinet",
    "type": "exhibit identity",
    "displayId": "MH-DISP-008",
    "displayLabel": "Case 8 / D. Richard Reynolds memorial cabinet"
  },
  {
    "id": "MH-EXH-MAP-009",
    "name": "Harold W. Arndt Collection",
    "type": "exhibit identity",
    "displayId": "MH-DISP-009",
    "displayLabel": "Case 9 / Harold W. Arndt Collection"
  },
  {
    "id": "MH-EXH-MAP-010",
    "name": "First window-sill mineral display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-010",
    "displayLabel": "Case 10 / First window-sill mineral display"
  },
  {
    "id": "MH-EXH-MAP-011",
    "name": "Minerals from the Dr. George Smith Collection — about 1835",
    "type": "exhibit identity",
    "displayId": "MH-DISP-011",
    "displayLabel": "Case 11 / Minerals from the Dr. George Smith Collection — about 1835"
  },
  {
    "id": "MH-EXH-MAP-012",
    "name": "Four large mineral specimens under acrylic covers",
    "type": "exhibit identity",
    "displayId": "MH-DISP-012",
    "displayLabel": "Case 12 / Four large mineral specimens under acrylic covers"
  },
  {
    "id": "MH-EXH-MAP-013",
    "name": "Second window-sill mineral display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-013",
    "displayLabel": "Case 13 / Second window-sill mineral display"
  },
  {
    "id": "MH-EXH-MAP-014",
    "name": "Petrified-wood display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-014",
    "displayLabel": "Case 14 / Petrified-wood display"
  },
  {
    "id": "MH-EXH-MAP-015",
    "name": "Philadelphia Region / Coaquannock framed map",
    "type": "exhibit identity",
    "displayId": "MH-DISP-015",
    "displayLabel": "Case 15 / Philadelphia Region / Coaquannock framed map"
  },
  {
    "id": "MH-EXH-MAP-016",
    "name": "Third window-sill mineral display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-016",
    "displayLabel": "Case 16 / Third window-sill mineral display"
  },
  {
    "id": "MH-EXH-MAP-017",
    "name": "John Cassin display and mining-district map",
    "type": "exhibit identity",
    "displayId": "MH-DISP-017",
    "displayLabel": "Case 17 / John Cassin display and mining-district map"
  },
  {
    "id": "MH-EXH-MAP-018",
    "name": "Corner specimen cabinet / left unit of 18–19 pair",
    "type": "exhibit identity",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18–19 pair"
  },
  {
    "id": "MH-EXH-MAP-019",
    "name": "Door-side specimen cabinet / right unit of 18–19 pair",
    "type": "exhibit identity",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18–19 pair"
  },
  {
    "id": "MH-EXH-007",
    "name": "Basic Rock Collection",
    "type": "exhibit poster",
    "displayId": "MH-DISP-019",
    "displayLabel": "Door-side specimen cabinet / right unit of 18–19 pair"
  },
  {
    "id": "DCIS-WR-000677",
    "displayId": "MH-DISP-001",
    "displayLabel": "1 Branegan",
    "name": "Selenite on Dolomite",
    "type": "specimen",
    "description": "Gypsum can form bladed, tabular and fibrous aggregates and has perfect cleavage in one direction. Dolomite is a calcium-magnesium carbonate that commonly forms rhombohedral crystals; some crystal faces are curved.",
    "observationPrompt": "Can you compare thin blade edges with broader faces?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000677-normal.webp",
        "alt": "Selenite on Dolomite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000678",
    "displayId": "MH-DISP-001",
    "displayLabel": "1 Branegan",
    "name": "Gypsum “Ram’s Horn”",
    "type": "specimen",
    "description": "Gypsum can form bladed, tabular and fibrous aggregates and has perfect cleavage in one direction.",
    "observationPrompt": "Can you follow the curve from the base to the tip?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000678-normal.webp",
        "alt": "Gypsum “Ram’s Horn” — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000060",
    "displayId": "MH-DISP-002",
    "displayLabel": "2 Local Stones",
    "name": "Granite — circular sample",
    "type": "specimen",
    "description": "Start with the circular cut face: it lets you compare grains without a rough outer surface getting in the way. The label calls this granite. Compare its individual pale and dark patches with the streakier metamorphic rocks in the cabinet.",
    "observationPrompt": "Can you trace the boundaries between the pale and dark grains?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000060-normal.webp",
        "alt": "Granite — circular sample — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000061",
    "displayId": "MH-DISP-002",
    "displayLabel": "2 Local Stones",
    "name": "Amphibolite gneiss — circular sample",
    "type": "specimen",
    "description": "This circular cut face reveals the texture of amphibolite gneiss. Compare its pale and dark areas with the granite sample: the same preparation can reveal different rock textures.",
    "observationPrompt": "Are the pale and dark areas scattered or arranged in streaks?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000061-normal.webp",
        "alt": "Amphibolite gneiss — circular sample — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000082",
    "displayId": "MH-DISP-003",
    "displayLabel": "3 PA",
    "name": "Beryl & Microcline",
    "type": "specimen",
    "description": "The blue-green prisms and their pinkish-brown host make a useful first puzzle: one rock can contain more than one mineral. The card names beryl and microcline and links this specimen to Mineral Hill in Delaware County. Beryl commonly makes prismatic crystals; microcline is a feldspar. Compare the long crystal faces with the broad host surface. Color alone does not establish a gem variety or value.",
    "observationPrompt": "How many separate crystal faces can you follow before they disappear into the host?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000082-normal.webp",
        "alt": "Beryl & Microcline — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000083",
    "displayId": "MH-DISP-003",
    "displayLabel": "3 PA",
    "name": "Albite",
    "type": "specimen",
    "description": "Look across the pale blocky surfaces and reflective patches. Albite is a sodium-rich feldspar and can form tabular crystals, aggregates and massive material.",
    "observationPrompt": "Which surfaces are broad and flat, and which are rough?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000083-normal.webp",
        "alt": "Albite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000037",
    "displayId": "MH-DISP-004",
    "displayLabel": "4 Fluorescent",
    "name": "Scheelite",
    "type": "specimen",
    "description": "The label identifies scheelite. Its characteristic blue fluorescence is connected to tungstate in its own chemical structure—not every fluorescent mineral needs a trace impurity to glow.",
    "observationPrompt": "Where are the pale patches on the rough surface?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000037-normal.webp",
        "alt": "Scheelite — photographed display detail",
        "label": "Normal light"
      },
      {
        "src": "/assets/mineral-hall/DCIS-WR-000037-uv.webp",
        "alt": "Scheelite photographed under ultraviolet illumination",
        "label": "UV light"
      }
    ]
  },
  {
    "id": "DCIS-WR-000038",
    "displayId": "MH-DISP-004",
    "displayLabel": "4 Fluorescent",
    "name": "Agrellite",
    "type": "specimen",
    "description": "Compare the layered-looking surfaces in this pale slab. The standard mineral name is Agrellite; the card spells it Agrelite.",
    "observationPrompt": "Which edges make the layered texture easiest to see?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000038-normal.webp",
        "alt": "Agrellite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000145",
    "displayId": "MH-DISP-005",
    "displayLabel": "5 U.S.",
    "name": "Gypsum var. Selenite",
    "type": "specimen",
    "description": "Follow the broad, translucent layers in this selenite slab. Selenite is a crystalline variety of gypsum, whose structure includes water. Transparency alone would not distinguish it from quartz or calcite.",
    "observationPrompt": "Which edges reveal the slab’s layers most clearly?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000145-normal.webp",
        "alt": "Gypsum var. Selenite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000146",
    "displayId": "MH-DISP-005",
    "displayLabel": "5 U.S.",
    "name": "Beryl",
    "type": "specimen",
    "description": "Beryl can form prismatic crystals and occurs in a range of colours. Compare the crystal-like forms in this pale specimen with the surrounding rough material.",
    "observationPrompt": "Can you separate the crystal-like forms from the surrounding rough material?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000146-normal.webp",
        "alt": "Beryl — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000174",
    "displayId": "MH-DISP-006",
    "displayLabel": "6 New Acq.",
    "name": "Quartz var. Chalcedony",
    "type": "specimen",
    "description": "The rounded cavities invite a closer look at the card: it calls this chalcedony after Tampa Bay Coral. Quartz can occur as fine-grained chalcedony.",
    "observationPrompt": "Can you follow the curved edges of a cavity?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000174-normal.webp",
        "alt": "Quartz var. Chalcedony — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000175",
    "displayId": "MH-DISP-006",
    "displayLabel": "6 New Acq.",
    "name": "Rhodochrosite",
    "type": "specimen",
    "description": "This rounded pink-red mass shows that minerals need not form isolated sharp crystals. Rhodochrosite is a manganese carbonate that can form rounded aggregates as well as rhombohedral crystals.",
    "observationPrompt": "Can you follow the rounded surfaces across the mass?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000175-normal.webp",
        "alt": "Rhodochrosite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000201",
    "displayId": "MH-DISP-007",
    "displayLabel": "7 World",
    "name": "Rose Quartz",
    "type": "specimen",
    "description": "The large pink rough mass shows quartz without the familiar pointed silhouette. Quartz can be massive as well as crystalline; rose quartz is a colour variety, not a separate mineral species.",
    "observationPrompt": "How does the rough surface differ from a pointed crystal?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000201-normal.webp",
        "alt": "Rose Quartz — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000202",
    "displayId": "MH-DISP-007",
    "displayLabel": "7 World",
    "name": "Dover Flint",
    "type": "specimen",
    "description": "The pale slab with dark rounded areas is labelled Dover Flint. Flint belongs to the fine-grained silica family: crystals can be too small to distinguish even when a rock is made largely of quartz.",
    "observationPrompt": "Follow the boundary of a dark rounded area. Does it cut across the slab or sit within it?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000202-normal.webp",
        "alt": "Dover Flint — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000241",
    "displayId": "MH-DISP-008",
    "displayLabel": "8 Reynolds",
    "name": "Quartz",
    "type": "specimen",
    "description": "Quartz is silicon dioxide and can form pointed prismatic crystals or massive material. Compare the broad surfaces and rough edges of this piece.",
    "observationPrompt": "From outside the case, compare the outline, surface texture and light–dark contrasts. Which feature would help you describe this material to someone else?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000241-normal.webp",
        "alt": "Quartz — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000242",
    "displayId": "MH-DISP-008",
    "displayLabel": "8 Reynolds",
    "name": "Beryl",
    "type": "specimen",
    "description": "Beryl can form long prismatic crystals, but also granular or compact material. Its mineral name does not establish a gemstone variety.",
    "observationPrompt": "From outside the case, compare the outline, surface texture and light–dark contrasts. Which feature would help you describe this material to someone else?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000242-normal.webp",
        "alt": "Beryl — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000307",
    "displayId": "MH-DISP-009",
    "displayLabel": "9 Arndt",
    "name": "CALCITE",
    "type": "specimen",
    "description": "Smaller pale crystalline unit left of center. Calcite is calcium carbonate. Its perfect cleavage produces rhombohedral breaks; a flat face alone does not tell us whether it grew as a crystal face or formed by breakage.",
    "observationPrompt": "Which edges meet at slanting angles, and which surfaces look rough rather than flat?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000307-normal.webp",
        "alt": "CALCITE — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000309",
    "displayId": "MH-DISP-009",
    "displayLabel": "9 Arndt",
    "name": "FELDSPAR",
    "type": "specimen",
    "description": "Feldspar names a group of aluminosilicates containing potassium, sodium or calcium. Compare the broad flat surfaces with the rough granular areas in this pale crystalline mass.",
    "observationPrompt": "Compare broad flat surfaces with rough granular areas. Can you find a repeated direction?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000309-normal.webp",
        "alt": "FELDSPAR — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000389",
    "displayId": "MH-DISP-011",
    "displayLabel": "11 Wall",
    "name": "MALACHITE",
    "type": "specimen",
    "description": "Malachite is a green copper mineral commonly formed in the oxidation zone of copper deposits. Reactions near the surface can transform earlier copper-bearing material.",
    "observationPrompt": "Compare the darker and lighter mottling. Is the contrast on a surface or along a visible edge?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000389-normal.webp",
        "alt": "MALACHITE — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000397",
    "displayId": "MH-DISP-011",
    "displayLabel": "11 Wall",
    "name": "Tremolite",
    "type": "specimen",
    "description": "Tremolite is a calcium-magnesium amphibole that can occur as prismatic, bladed, granular or fibrous aggregates. It commonly forms during metamorphism of suitable calcium- and magnesium-rich rocks.",
    "observationPrompt": "From outside the case, compare broad surfaces with any repeated ridges; do they run in one direction?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000397-normal.webp",
        "alt": "Tremolite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000429",
    "displayId": "MH-DISP-012",
    "displayLabel": "12 Ground",
    "name": "MAGNETITE",
    "type": "specimen",
    "description": "Dark gray rough angular upright mass, with left/lower outline partly overlapped by pale foreground material. Magnetite is an iron oxide known for strong magnetism. It occurs in varied igneous, metamorphic and sedimentary settings and may be granular or massive rather than a sharply formed crystal. Magnetism is a general mineral property, not a test performed on this displayed mass.",
    "observationPrompt": "From outside the cover, trace the dark mass until its edge disappears behind the pale foreground assembly; do not test or handle it.",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000429-normal.webp",
        "alt": "MAGNETITE — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000430",
    "displayId": "MH-DISP-012",
    "displayLabel": "12 Ground",
    "name": "MICROCLINE & HORNBLENDE",
    "type": "specimen",
    "description": "Blocky mass with pink-brown areas and dark angular lower/side portions. Clear gap separates it from the large cream unit to its right. Microcline is a potassium feldspar with two prominent cleavage directions meeting near right angles. Hornblende is a broad amphibole name associated with variable chemistry and double-chain silicate structures. The paired label invites comparison of mineral textures, but pink and dark areas cannot be assigned to either name solely from color.",
    "observationPrompt": "Compare the blocky pink-brown areas with the dark angular portions. Which contacts are visible?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000430-normal.webp",
        "alt": "MICROCLINE & HORNBLENDE — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000432",
    "displayId": "MH-DISP-018",
    "displayLabel": "18 Corner",
    "name": "Geode",
    "type": "specimen",
    "description": "A geode is a mineral-lined rock cavity: crystals can grow inward into open space. Its hollow form describes an arrangement, not a mineral species.",
    "observationPrompt": "Compare the rough outer wall with the crystal-lined cavity. Where do crystal tips point?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000432-normal.webp",
        "alt": "Geode — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000433",
    "displayId": "MH-DISP-018",
    "displayLabel": "18 Corner",
    "name": "Soapstone",
    "type": "specimen",
    "description": "Soapstone is a metamorphic rock name, not a single mineral species. Heat and pressure can change a rock without leaving the aligned layers characteristic of foliated rocks.",
    "observationPrompt": "Does the flattened slab show internal layers, or is its flatness mainly its overall shape? Observe without touching.",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000433-normal.webp",
        "alt": "Soapstone — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000448",
    "displayId": "MH-DISP-019",
    "displayLabel": "19 Near door",
    "name": "Feldspar",
    "type": "specimen",
    "description": "Feldspar is a group of aluminosilicate minerals containing potassium, sodium or calcium.",
    "observationPrompt": "Search the pale triangular specimen for repeated planar surfaces, keeping its overall broken shape separate from crystal form.",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000448-normal.webp",
        "alt": "Feldspar — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000449",
    "displayId": "MH-DISP-019",
    "displayLabel": "19 Near door",
    "name": "Dolomite",
    "type": "specimen",
    "description": "Dolomite is a calcium-magnesium carbonate with rhombohedral cleavage. Look for repeated inclined flat surfaces on the gray block.",
    "observationPrompt": "Can you find repeated inclined flat surfaces?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000449-normal.webp",
        "alt": "Dolomite — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000493",
    "displayId": "MH-WORK-MINERAL-ISLAND",
    "displayLabel": "Island collection",
    "name": "Almandine",
    "type": "specimen",
    "description": "Almandine is an iron-bearing member of the garnet group. Its crystals can be dodecahedral or trapezohedral, while aggregates may be granular.",
    "observationPrompt": "Can you distinguish projecting crystal faces from the surrounding matrix?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000493-normal.webp",
        "alt": "Almandine — photographed display detail"
      }
    ]
  },
  {
    "id": "DCIS-WR-000494",
    "displayId": "MH-WORK-MINERAL-ISLAND",
    "displayLabel": "Island collection",
    "name": "Limonite",
    "type": "specimen",
    "description": "Limonite is a broad name for impure hydrated iron-oxide material, often formed by alteration of other iron minerals.",
    "observationPrompt": "How do the ochre patches contrast with the dark rough surface?",
    "images": [
      {
        "src": "/assets/mineral-hall/DCIS-WR-000494-normal.webp",
        "alt": "Limonite — photographed display detail"
      }
    ]
  }
];
export function specimensForDisplay(displayId: string) {
  return mineralSpecimenRecords.filter(record => record.displayId === displayId);
}
