export type MineralEvidenceStatus = "matched" | "candidate" | "partial" | "located";

export type MineralMapItem = {
  id: string;
  displayId: string;
  label: string;
  summary: string;
  evidence: string;
  confidence: string;
  status: MineralEvidenceStatus;
  x: number;
  y: number;
  width?: number;
  height?: number;
};

export type MineralSpecimenRecord = {
  id: string;
  name: string;
  type: string;
  displayId: string;
  displayLabel: string;
  evidence: string[];
  labelDetail?: string;
  confidence: "confirmed" | "medium" | "partial";
  publicUse: "searchable" | "candidate" | "partial";
};

export type MissingShot = {
  priority: "P1" | "P2" | "P3";
  target: string;
  why: string;
};

// Generated by knowledge-base/recovery-2026-09-15/synchronize-records.py
export const mineralMapItems: MineralMapItem[] = [
{
    id: "entry",
    displayId: "MH-DISP-ENTRY-001",
    label: "Entry",
    summary: "Public Mineral Hall threshold from the second entrance. The consumer map starts here and does not expose staff-side room geometry.",
    evidence: "IMG-012, IMG-013, video t001-t013",
    confidence: "confirmed route origin",
    status: "matched",
    x: 310,
    y: 890,
    width: 126,
    height: 54,
  },
{
    id: "shells",
    displayId: "MH-DISP-SHELLS-001",
    label: "Shells",
    summary: "Shells, fossils, and kid take-home material near the Mineral Hall door. Placement comes from Brendan's correction; the first three matching Telegram photos are still unresolved.",
    evidence: "Brendan correction; IMG-023 route context",
    confidence: "reported content, confirmed placement",
    status: "partial",
    x: 480,
    y: 805,
    width: 116,
    height: 54,
  },
{
    id: "1",
    displayId: "MH-DISP-001",
    label: "1 Branegan",
    summary: "Branegan Cabinet. Inner-wall run after shells; Branegan Cabinet",
    evidence: "IMG-024; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 442,
    y: 700,
    width: 158,
    height: 54,
  },
{
    id: "2",
    displayId: "MH-DISP-002",
    label: "2 Local Stones",
    summary: "Branegan Cabinet B / Local Building Stones. Next inner-wall case; Branegan Cabinet B / Local Building Stones",
    evidence: "IMG-025; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 442,
    y: 550,
    width: 150,
    height: 54,
  },
{
    id: "3",
    displayId: "MH-DISP-003",
    label: "3 PA",
    summary: "Minerals from Pennsylvania. Interior wall of deeper L recess",
    evidence: "IMG-027; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 354,
    y: 447,
    width: 146,
    height: 54,
  },
{
    id: "4",
    displayId: "MH-DISP-004",
    label: "4 Fluorescent",
    summary: "Fluorescent mineral case. Interior wall of deeper L recess; fluorescent case",
    evidence: "IMG-028; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 255,
    y: 447,
    width: 150,
    height: 54,
  },
{
    id: "5",
    displayId: "MH-DISP-005",
    label: "5 U.S.",
    summary: "Minerals from United States. Standalone inner wall",
    evidence: "IMG-029; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 105,
    y: 352,
    width: 142,
    height: 54,
  },
{
    id: "6",
    displayId: "MH-DISP-006",
    label: "6 New Acq.",
    summary: "Minerals from World-Wide (New Acquisitions). First case of back-wall run",
    evidence: "IMG-031; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 170,
    y: 266,
    width: 158,
    height: 54,
  },
{
    id: "7",
    displayId: "MH-DISP-007",
    label: "7 World",
    summary: "Minerals from World-Wide. Back-wall run after 6",
    evidence: "IMG-032; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 310,
    y: 266,
    width: 134,
    height: 54,
  },
{
    id: "8",
    displayId: "MH-DISP-008",
    label: "8 Reynolds",
    summary: "D. Richard Reynolds memorial cabinet. Back-wall run after 7",
    evidence: "IMG-035; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 435,
    y: 266,
    width: 134,
    height: 54,
  },
{
    id: "9",
    displayId: "MH-DISP-009",
    label: "9 Arndt",
    summary: "Harold W. Arndt Collection. Last back-wall case before corner door",
    evidence: "IMG-036; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 550,
    y: 266,
    width: 144,
    height: 54,
  },
{
    id: "10",
    displayId: "MH-DISP-010",
    label: "10 Sill",
    summary: "First window-sill mineral display. First window sill",
    evidence: "IMG-030; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 748,
    y: 335,
    width: 116,
    height: 48,
  },
{
    id: "11",
    displayId: "MH-DISP-011",
    label: "11 Wall",
    summary: "Minerals from the Dr. George Smith Collection \u2014 about 1835. Between first and second windows, wall level",
    evidence: "IMG-033; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 753,
    y: 457,
    width: 116,
    height: 48,
  },
{
    id: "12",
    displayId: "MH-DISP-012",
    label: "12 Ground",
    summary: "Four large mineral specimens under acrylic covers. Between first and second windows, ground level",
    evidence: "IMG-034; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 680,
    y: 457,
    width: 116,
    height: 48,
  },
{
    id: "13",
    displayId: "MH-DISP-013",
    label: "13 Sill",
    summary: "Second window-sill mineral display. Second window sill",
    evidence: "IMG-037; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 749,
    y: 595,
    width: 116,
    height: 48,
  },
{
    id: "14",
    displayId: "MH-DISP-014",
    label: "14 Ground",
    summary: "Petrified-wood display. Between second and third windows, ground level",
    evidence: "IMG-038; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 680,
    y: 735,
    width: 116,
    height: 48,
  },
{
    id: "15",
    displayId: "MH-DISP-015",
    label: "15 Wall",
    summary: "Philadelphia Region / Coaquannock framed map. Between second and third windows, wall level",
    evidence: "IMG-039; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 753,
    y: 735,
    width: 116,
    height: 48,
  },
{
    id: "16",
    displayId: "MH-DISP-016",
    label: "16 Sill",
    summary: "Third window-sill mineral display. Third window sill",
    evidence: "IMG-040; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 749,
    y: 850,
    width: 116,
    height: 48,
  },
{
    id: "17",
    displayId: "MH-DISP-017",
    label: "17 Cassin",
    summary: "John Cassin display and mining-district map. Window-side wall immediately right of last window, near corner; John Cassin",
    evidence: "IMG-041; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 755,
    y: 930,
    width: 104,
    height: 48,
  },
{
    id: "18",
    displayId: "MH-DISP-018",
    label: "18 Corner",
    summary: "Corner specimen cabinet / left unit of 18\u201319 pair. Starts at corner",
    evidence: "IMG-042; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 688,
    y: 965,
    width: 104,
    height: 48,
  },
{
    id: "19",
    displayId: "MH-DISP-019",
    label: "19 Near door",
    summary: "Door-side specimen cabinet / right unit of 18\u201319 pair. Closer to Special Collections/front-wall door",
    evidence: "IMG-043; reconciled source ledger 2026-09-15",
    confidence: "identity reconciled; specimen inventory separate",
    status: "matched",
    x: 621,
    y: 965,
    width: 126,
    height: 48,
  }
];

export const mineralSpecimenRecords: MineralSpecimenRecord[] = [
  {
    "id": "MH-SPEC-001",
    "name": "Sulfur, Aragonite, Celestine",
    "type": "specimen/group label",
    "displayId": "MH-DISP-001",
    "displayLabel": "Case 1 / Branegan Cabinet",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/15007579-763a-4de4-a784-367bae0d653c.jpg"
    ],
    "labelDetail": "Girgenti, Italy (Sicily); probably collected before 1930 Label and details confirmed by enlarged source-photo inspection on 2026-09-15.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-002",
    "name": "Amphibolite Gneiss",
    "type": "specimen/group label",
    "displayId": "MH-DISP-002",
    "displayLabel": "Case 2 / Branegan Cabinet B / Local Building Stones",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/cef7a668-be4c-421b-b65d-11ae0ffd2d64.jpg"
    ],
    "labelDetail": "Locality not transcribed. ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-003",
    "name": "Quartz var. Smoky",
    "type": "specimen/group label",
    "displayId": "MH-DISP-010",
    "displayLabel": "Case 10 / First window-sill mineral display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/cbc03750-643b-4de2-9b09-924fd45d3262.jpg"
    ],
    "labelDetail": "Upper Darby, Pa. ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-004",
    "name": "Barite on Fluorite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-010",
    "displayLabel": "Case 10 / First window-sill mineral display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/cbc03750-643b-4de2-9b09-924fd45d3262.jpg"
    ],
    "labelDetail": "Cumberland, England ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-005",
    "name": "Quartz var. Rose",
    "type": "specimen/group label",
    "displayId": "MH-DISP-013",
    "displayLabel": "Case 13 / Second window-sill mineral display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/10a66a50-4958-4ebc-a172-4437aefe1844.jpg"
    ],
    "labelDetail": "Brazil ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-006",
    "name": "Limonite/Goethite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-013",
    "displayLabel": "Case 13 / Second window-sill mineral display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/10a66a50-4958-4ebc-a172-4437aefe1844.jpg"
    ],
    "labelDetail": "Henderson, Pa. ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-007",
    "name": "Petrified Wood",
    "type": "specimen/group label",
    "displayId": "MH-DISP-014",
    "displayLabel": "Case 14 / Petrified-wood display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0255b566-c982-4060-b395-d6ec3deb875f.jpg"
    ],
    "labelDetail": "Arizona ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-008",
    "name": "Datolite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-016",
    "displayLabel": "Case 16 / Third window-sill mineral display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/b3cb0bb5-c6f2-470a-bd93-2fa37ead7785.jpg"
    ],
    "labelDetail": "Westfield, MA ",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-009",
    "name": "Calcite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-016",
    "displayLabel": "Case 16 / Third window-sill mineral display",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/b3cb0bb5-c6f2-470a-bd93-2fa37ead7785.jpg"
    ],
    "labelDetail": "York, York Co., Pa.; quarry name partially readable (Baker \u2026 Quarry) Do not expand the quarry name without a better read.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-010",
    "name": "Soapstone",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-011",
    "name": "Geode",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-012",
    "name": "Limestone",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-013",
    "name": "Tourmaline",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-014",
    "name": "Calcite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Thomasville, PA. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-015",
    "name": "Garnet",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-016",
    "name": "Feldspar",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-017",
    "name": "Mica",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-018",
    "name": "Dolomite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-019",
    "name": "Limonite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-020",
    "name": "Granite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-021",
    "name": "Graphite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-022",
    "name": "Coal",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-023",
    "name": "Lava",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-024",
    "name": "Pumice",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-025",
    "name": "Shale",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-026",
    "name": "Malachite/Azurite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-027",
    "name": "Pegmatite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-028",
    "name": "Slate",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-029",
    "name": "Fluorite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-030",
    "name": "Quartz",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-031",
    "name": "Rose Quartz",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-032",
    "name": "Halite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-033",
    "name": "Hematite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-034",
    "name": "Fern Fossil",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-035",
    "name": "Sandstone",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-036",
    "name": "Beryl",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Rumney, NH. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-037",
    "name": "Dravite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "St. Lawrence Co., NY. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens. Dravite is the brown specimen at the bottom of Case 18, not the pink/green neighboring specimen in Case 19.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-038",
    "name": "Cryolite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "labelDetail": "Ivigtut, Greenland. Cabinet assignment verified against full cabinet photograph; old video frame ranges may include neighboring specimens.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-039",
    "name": "Malachite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0e573b08-4524-456a-a0e9-4860a3e266f5.jpg"
    ],
    "labelDetail": "Locality not transcribed. Prior positive identification retained under Brendan\u2019s 90-percent rule; cabinet location resolved, individual label not independently re-read at sufficient clarity in this checkpoint.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-040",
    "name": "Graphite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0e573b08-4524-456a-a0e9-4860a3e266f5.jpg"
    ],
    "labelDetail": "Locality not transcribed. Prior positive identification retained under Brendan\u2019s 90-percent rule; cabinet location resolved, individual label not independently re-read at sufficient clarity in this checkpoint.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-041",
    "name": "Magnetite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0e573b08-4524-456a-a0e9-4860a3e266f5.jpg"
    ],
    "labelDetail": "Locality not transcribed. Prior positive identification retained under Brendan\u2019s 90-percent rule; cabinet location resolved, individual label not independently re-read at sufficient clarity in this checkpoint.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-042",
    "name": "Limonite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0e573b08-4524-456a-a0e9-4860a3e266f5.jpg"
    ],
    "labelDetail": "Locality not transcribed. Prior positive identification retained under Brendan\u2019s 90-percent rule; cabinet location resolved, individual label not independently re-read at sufficient clarity in this checkpoint.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-043",
    "name": "Chalcopyrite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0e573b08-4524-456a-a0e9-4860a3e266f5.jpg"
    ],
    "labelDetail": "Locality not transcribed. Prior positive identification retained under Brendan\u2019s 90-percent rule; cabinet location resolved, individual label not independently re-read at sufficient clarity in this checkpoint.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-044",
    "name": "Azurite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/0e573b08-4524-456a-a0e9-4860a3e266f5.jpg"
    ],
    "labelDetail": "Locality not transcribed. Prior positive identification retained under Brendan\u2019s 90-percent rule; cabinet location resolved, individual label not independently re-read at sufficient clarity in this checkpoint.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-045",
    "name": "Orthoclase, variety Cassinite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-017",
    "displayLabel": "Case 17 / John Cassin display and mining-district map",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/bb27b410-33db-49b2-918b-c5bae6efbd22.jpg"
    ],
    "labelDetail": "Blue Hill, Upper Providence Township, Delaware County, Pa. Label and details confirmed by enlarged source-photo inspection on 2026-09-15.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-046",
    "name": "Shale",
    "type": "specimen/group label",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/9350db3b-1bc2-471d-a02d-45c2398b47ed.jpg"
    ],
    "labelDetail": "Locality not transcribed. Separate from Case 19 shale MH-SPEC-025; old record merged evidence from both cabinets.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-047",
    "name": "Pectolite & Prehnite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-012",
    "displayLabel": "Case 12 / Four large mineral specimens under acrylic covers",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/4a9b0fb5-1b7a-4f48-a02d-f82cc372a3df.jpg"
    ],
    "labelDetail": "Paterson, New Jersey Read in source-to-exhibit checkpoint from closeup of the four-specimen plinth.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-048",
    "name": "Magnetite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-012",
    "displayLabel": "Case 12 / Four large mineral specimens under acrylic covers",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/4a9b0fb5-1b7a-4f48-a02d-f82cc372a3df.jpg"
    ],
    "labelDetail": "Ontario, Canada Read in source-to-exhibit checkpoint from closeup of the four-specimen plinth.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-049",
    "name": "Microcline & Hornblende",
    "type": "specimen/group label",
    "displayId": "MH-DISP-012",
    "displayLabel": "Case 12 / Four large mineral specimens under acrylic covers",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/4a9b0fb5-1b7a-4f48-a02d-f82cc372a3df.jpg"
    ],
    "labelDetail": "Ontario, Canada Read in source-to-exhibit checkpoint from closeup of the four-specimen plinth.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-SPEC-050",
    "name": "Calcite",
    "type": "specimen/group label",
    "displayId": "MH-DISP-012",
    "displayLabel": "Case 12 / Four large mineral specimens under acrylic covers",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/4a9b0fb5-1b7a-4f48-a02d-f82cc372a3df.jpg"
    ],
    "labelDetail": "Thomasville, Pa. Read in source-to-exhibit checkpoint from closeup of the four-specimen plinth.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-001",
    "name": "Branegan Cabinet",
    "type": "exhibit identity",
    "displayId": "MH-DISP-001",
    "displayLabel": "Case 1 / Branegan Cabinet",
    "evidence": [
      "IMG-024"
    ],
    "labelDetail": "Inner-wall run after shells; Branegan Cabinet",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-002",
    "name": "Branegan Cabinet B / Local Building Stones",
    "type": "exhibit identity",
    "displayId": "MH-DISP-002",
    "displayLabel": "Case 2 / Branegan Cabinet B / Local Building Stones",
    "evidence": [
      "IMG-025"
    ],
    "labelDetail": "Next inner-wall case; Branegan Cabinet B / Local Building Stones",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-003",
    "name": "Minerals from Pennsylvania",
    "type": "exhibit identity",
    "displayId": "MH-DISP-003",
    "displayLabel": "Case 3 / Minerals from Pennsylvania",
    "evidence": [
      "IMG-027"
    ],
    "labelDetail": "Interior wall of deeper L recess",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-004",
    "name": "Fluorescent mineral case",
    "type": "exhibit identity",
    "displayId": "MH-DISP-004",
    "displayLabel": "Case 4 / Fluorescent mineral case",
    "evidence": [
      "IMG-028"
    ],
    "labelDetail": "Interior wall of deeper L recess; fluorescent case Turn off normal case lights; one switch makes some minerals glow, another makes more glow.",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-005",
    "name": "Minerals from United States",
    "type": "exhibit identity",
    "displayId": "MH-DISP-005",
    "displayLabel": "Case 5 / Minerals from United States",
    "evidence": [
      "IMG-029"
    ],
    "labelDetail": "Standalone inner wall",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-006",
    "name": "Minerals from World-Wide (New Acquisitions)",
    "type": "exhibit identity",
    "displayId": "MH-DISP-006",
    "displayLabel": "Case 6 / Minerals from World-Wide (New Acquisitions)",
    "evidence": [
      "IMG-031"
    ],
    "labelDetail": "First case of back-wall run",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-007",
    "name": "Minerals from World-Wide",
    "type": "exhibit identity",
    "displayId": "MH-DISP-007",
    "displayLabel": "Case 7 / Minerals from World-Wide",
    "evidence": [
      "IMG-032"
    ],
    "labelDetail": "Back-wall run after 6",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-008",
    "name": "D. Richard Reynolds memorial cabinet",
    "type": "exhibit identity",
    "displayId": "MH-DISP-008",
    "displayLabel": "Case 8 / D. Richard Reynolds memorial cabinet",
    "evidence": [
      "IMG-035"
    ],
    "labelDetail": "Back-wall run after 7",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-009",
    "name": "Harold W. Arndt Collection",
    "type": "exhibit identity",
    "displayId": "MH-DISP-009",
    "displayLabel": "Case 9 / Harold W. Arndt Collection",
    "evidence": [
      "IMG-036"
    ],
    "labelDetail": "Last back-wall case before corner door",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-010",
    "name": "First window-sill mineral display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-010",
    "displayLabel": "Case 10 / First window-sill mineral display",
    "evidence": [
      "IMG-030"
    ],
    "labelDetail": "First window sill",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-011",
    "name": "Minerals from the Dr. George Smith Collection \u2014 about 1835",
    "type": "exhibit identity",
    "displayId": "MH-DISP-011",
    "displayLabel": "Case 11 / Minerals from the Dr. George Smith Collection \u2014 about 1835",
    "evidence": [
      "IMG-033"
    ],
    "labelDetail": "Between first and second windows, wall level",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-012",
    "name": "Four large mineral specimens under acrylic covers",
    "type": "exhibit identity",
    "displayId": "MH-DISP-012",
    "displayLabel": "Case 12 / Four large mineral specimens under acrylic covers",
    "evidence": [
      "IMG-034"
    ],
    "labelDetail": "Between first and second windows, ground level",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-013",
    "name": "Second window-sill mineral display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-013",
    "displayLabel": "Case 13 / Second window-sill mineral display",
    "evidence": [
      "IMG-037"
    ],
    "labelDetail": "Second window sill",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-014",
    "name": "Petrified-wood display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-014",
    "displayLabel": "Case 14 / Petrified-wood display",
    "evidence": [
      "IMG-038"
    ],
    "labelDetail": "Between second and third windows, ground level",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-015",
    "name": "Philadelphia Region / Coaquannock framed map",
    "type": "exhibit identity",
    "displayId": "MH-DISP-015",
    "displayLabel": "Case 15 / Philadelphia Region / Coaquannock framed map",
    "evidence": [
      "IMG-039"
    ],
    "labelDetail": "Between second and third windows, wall level",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-016",
    "name": "Third window-sill mineral display",
    "type": "exhibit identity",
    "displayId": "MH-DISP-016",
    "displayLabel": "Case 16 / Third window-sill mineral display",
    "evidence": [
      "IMG-040"
    ],
    "labelDetail": "Third window sill",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-017",
    "name": "John Cassin display and mining-district map",
    "type": "exhibit identity",
    "displayId": "MH-DISP-017",
    "displayLabel": "Case 17 / John Cassin display and mining-district map",
    "evidence": [
      "IMG-041"
    ],
    "labelDetail": "Window-side wall immediately right of last window, near corner; John Cassin",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-018",
    "name": "Corner specimen cabinet / left unit of 18\u201319 pair",
    "type": "exhibit identity",
    "displayId": "MH-DISP-018",
    "displayLabel": "Case 18 / Corner specimen cabinet / left unit of 18\u201319 pair",
    "evidence": [
      "IMG-042"
    ],
    "labelDetail": "Starts at corner",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-MAP-019",
    "name": "Door-side specimen cabinet / right unit of 18\u201319 pair",
    "type": "exhibit identity",
    "displayId": "MH-DISP-019",
    "displayLabel": "Case 19 / Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "IMG-043"
    ],
    "labelDetail": "Closer to Special Collections/front-wall door",
    "confidence": "confirmed",
    "publicUse": "searchable"
  },
  {
    "id": "MH-EXH-007",
    "name": "Basic Rock Collection",
    "type": "exhibit poster",
    "displayId": "MH-DISP-019",
    "displayLabel": "Door-side specimen cabinet / right unit of 18\u201319 pair",
    "evidence": [
      "/home/precision_focused_solutions/.openclaw/media/inbound/c69b341d-d6f5-4fa5-bbb4-899f1eaa569d.jpg"
    ],
    "confidence": "confirmed",
    "publicUse": "searchable"
  }
];

// No new-photo requests until existing archives are exhausted.
export const mineralMissingShots: MissingShot[] = [{priority: "P2", target: "Review existing Pennsylvania closeups", why: "Six prior positive identifications need another saved-image check; no new photographs requested."}, {priority: "P2", target: "Review remaining saved cabinet and island labels", why: "Expand the inventory from existing material before identifying any actual capture gaps."}];

export function specimensForDisplay(displayId: string) {
 return mineralSpecimenRecords.filter(record => record.displayId === displayId);
}
