import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const sourceURL = new URL('../content/mineral-hall.public.json', import.meta.url);
export const outputURL = new URL('../src/mineralHallKnowledge.ts', import.meta.url);
// Defense in depth, not a substitute for reviewing every public string.
export const privatePattern = /(?:\/home\/|\.openclaw|media:\/\/|knowledge-base|recovery-2026|IMG-\d+|Telegram|Brendan|source_photo|legacy_source|label_audit_status|locality_status|labelDetail|publicUse|mineralMissingShots|StaffContent|staff-side|staff rear|staff seating|internal-building-reference|source-photo inspection|source-to-exhibit checkpoint|confirmed\/searchable|route verified|needs-photo-index)/i;
export function assertSafeText(text) {
  if (privatePattern.test(text)) throw new Error('Private/process content found in public data');
}
function keys(value, required, optional = []) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Expected object');
  if (required.some(k => !Object.hasOwn(value, k)) || Object.keys(value).some(k => ![...required, ...optional].includes(k))) throw new Error('Unexpected or missing public field');
}
function text(value) {
  if (typeof value !== 'string' || !value.trim()) throw new Error('Expected nonempty public text');
  assertSafeText(value);
}
export function validatePublic(data) {
  keys(data, ['schemaVersion', 'notice', 'mapItems', 'records']);
  if (data.schemaVersion !== 1) throw new Error('Unknown public schema');
  text(data.notice);
  if (data.notice !== 'Prototype reference, not an institutionally approved catalog. Selected labels only; identifications may be incomplete. Check the display labels.') throw new Error('Approval/coverage disclaimer must be retained');
  if (!Array.isArray(data.mapItems) || !Array.isArray(data.records)) throw new Error('Expected arrays');
  const ids = new Set(), displays = new Set(), records = new Set();
  for (const item of data.mapItems) {
    keys(item, ['id', 'displayId', 'label', 'summary', 'x', 'y', 'width', 'height']);
    for (const k of ['id', 'displayId', 'label', 'summary']) text(item[k]);
    for (const k of ['x', 'y', 'width', 'height']) if (!Number.isFinite(item[k]) || item[k] < 0) throw new Error('Invalid geometry');
    if (ids.has(item.id) || displays.has(item.displayId)) throw new Error('Duplicate map identity');
    ids.add(item.id); displays.add(item.displayId);
  }
  if (ids.size !== 21 || !['entry', 'shells', ...Array.from({length:19}, (_,i) => String(i+1))].every(id => ids.has(id))) throw new Error('Map coverage changed');
  for (const record of data.records) {
    keys(record, ['id', 'name', 'type', 'displayId', 'displayLabel'], ['description']);
    for (const value of Object.values(record)) text(value);
    if (records.has(record.id) || !displays.has(record.displayId)) throw new Error('Duplicate record or dangling display');
    records.add(record.id);
  }
  return data;
}
export function renderPublic(data) {
  validatePublic(data);
  return `// Generated by scripts/export-public.mjs from curated public content. Do not edit.\nexport type MineralMapItem = { id: string; displayId: string; label: string; summary: string; x: number; y: number; width: number; height: number };\nexport type MineralSpecimenRecord = { id: string; name: string; type: string; displayId: string; displayLabel: string; description?: string };\nexport const mineralPublicNotice = ${JSON.stringify(data.notice)};\nexport const mineralMapItems: MineralMapItem[] = ${JSON.stringify(data.mapItems, null, 2)};\nexport const mineralSpecimenRecords: MineralSpecimenRecord[] = ${JSON.stringify(data.records, null, 2)};\nexport function specimensForDisplay(displayId: string) {\n  return mineralSpecimenRecords.filter(record => record.displayId === displayId);\n}\n`;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const output = renderPublic(JSON.parse(readFileSync(sourceURL, 'utf8')));
  if (process.argv.includes('--check')) {
    if (readFileSync(outputURL, 'utf8') !== output) throw new Error('Public export drift: run npm run export:public and review the diff');
    console.log('Public export matches curated source');
  } else {
    writeFileSync(outputURL, output);
    console.log('Generated public-only Mineral Hall module');
  }
}
