import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync,readdirSync} from 'node:fs';
const load=p=>JSON.parse(readFileSync(new URL(p,import.meta.url)));
const g=load('../content/experiences/guide.json'),m=load('../content/experiences/mystery.json'),c=load('../content/mineral-hall.public.json');
function keys(o,allowed){assert.deepEqual(Object.keys(o).filter(k=>!allowed.includes(k)),[]);}
function unique(xs){assert.equal(new Set(xs).size,xs.length);}
function image(i,display){keys(i,['objectId','src','alt','label']);const row=c.records.find(r=>r.id===i.objectId);assert.ok(row);assert.equal(row.displayId,display);assert.ok(row.images.some(x=>x.src===i.src));assert.ok(existsSync(new URL('../public'+i.src,import.meta.url)));assert.ok(i.alt);}
function location(l){keys(l,['displayId','name','mapNumber','physicalSticker']);assert.equal(c.mapItems.find(x=>x.id===l.mapNumber)?.displayId,l.displayId);assert.equal(l.physicalSticker,({'3':'1','4':'3','7':'2'})[l.mapNumber]??null);}
test('strict reviewed experience allowlists, references and private exclusion',()=>{
 assert.deepEqual(readdirSync(new URL('../content/experiences',import.meta.url)).sort(),['guide.json','mystery.json']);
 keys(g,['schemaVersion','id','title','subtitle','introduction','orientation','safety','startStopId','stops','finish']);keys(m,['schemaVersion','id','title','subtitle','location','objectIds','entryNodeId','safety','nodes']);assert.equal(g.schemaVersion,1);assert.equal(m.schemaVersion,1);assert.equal(g.stops.length,5);assert.equal(m.nodes.length,6);unique(g.stops.map(s=>s.id));unique(m.nodes.map(s=>s.id));assert.ok(g.stops.some(s=>s.id===g.startStopId));assert.ok(m.nodes.some(n=>n.id===m.entryNodeId));
 for(const s of g.stops){keys(s,['id','title','location','objectIds','images','introduction','find','observation','objectStory','hallContext','deeper','notFound','nextStopId','nextDestination']);location(s.location);assert.ok(s.nextStopId==='end'||g.stops.some(t=>t.id===s.nextStopId));for(const i of s.images){image(i,s.location.displayId);assert.ok(s.objectIds.includes(i.objectId));}for(const id of s.objectIds)assert.equal(c.records.find(r=>r.id===id)?.displayId,s.location.displayId);keys(s.deeper,['label','text']);keys(s.notFound,['label','text']);}
 location(m.location);let choices=0;
 for(const n of m.nodes){keys(n,['id','kind','title','text','image','choices','initialState','states','comparisonNote','deeper','next','nextLabel','actions']);if(n.image)image(n.image,m.location.displayId);if(n.choices){unique(n.choices.map(x=>x.id));for(const x of n.choices){choices++;keys(x,['id','label','response','next']);assert.ok(x.response.length>30);assert.ok(m.nodes.some(t=>t.id===x.next));}}if(n.next)assert.ok(m.nodes.some(t=>t.id===n.next));if(n.states)for(const s of n.states){keys(s,['id','label','image','caption']);image(s.image,m.location.displayId);}if(n.deeper)keys(n.deeper,['label','text']);if(n.actions)for(const a of n.actions){keys(a,['label','nodeId','experienceId','stopId','displayId']);if(a.nodeId)assert.ok(m.nodes.some(t=>t.id===a.nodeId));else{assert.equal(a.experienceId,g.id);assert.ok(g.stops.some(t=>t.id===a.stopId&&(!a.displayId||t.location.displayId===a.displayId)));}}}
 assert.equal(choices,15);keys(g.finish,['title','text','primaryAction','secondaryAction']);keys(g.finish.primaryAction,['label','experienceId']);keys(g.finish.secondaryAction,['label','destination']);assert.equal(g.finish.primaryAction.experienceId,m.id);assert.equal(g.finish.secondaryAction.destination,'guide-stop-list');
 const reveal=m.nodes.find(n=>n.id==='reveal');assert.equal(reveal.initialState,'normal');assert.deepEqual(reveal.states.map(s=>s.id),['normal','uv']);assert.notEqual(reveal.states[0].image.src,reveal.states[1].image.src);assert.match(reveal.comparisonNote,/Framing differs/);
 const text=JSON.stringify([g,m]);for(const token of ['knowledge-base','/home/','private-source','source047','clarification','access_token','employee-only','basement'])assert.ok(!text.includes(token));
});
